---
# Copyright:: Copyright (c) 2017-present Sonatype, Inc. Apache License, Version 2.0.
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.35.36"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[nexus_repository_manager::default]
    verifier:
      inspec_tests:
        - test/smoke/default
  - name: docker
    run_list:
      - recipe[nexus_repository_manager::docker]
    verifier:
      inspec_tests:
        - test/smoke/docker
  - name: rh-docker
    run_list:
      - recipe[nexus_repository_manager::rh-docker]
    verifier:
      inspec_tests:
        - test/smoke/rh-docker
  - name: nexus_properties_configured
    run_list:
      - recipe[nexus_repository_manager::default]
    verifier:
      inspec_tests:
        - test/smoke/nexus_properties_configured
    attributes:
      nexus_repository_manager:
        properties:
          application_port: 8082
          application_host: 127.0.0.1
          context_path: "/test-context"
          clustered: true
          license_file: "/opt/sonatype/license.lic"
  - name: multicast_enabled
    run_list:
      - recipe[nexus_repository_manager::default]
    verifier:
      inspec_tests:
        - test/smoke/multicast_enabled
    attributes:
      nexus_repository_manager:
        hazelcast:
          multicast:
            enabled: true
            group: 123.4.5.6
            port: 54321
          aws:
            enabled: false
          tcp_ip:
            enabled: false
  - name: tcp_ip_enabled
    run_list:
      - recipe[nexus_repository_manager::default]
    verifier:
      inspec_tests:
        - test/smoke/tcp_ip_enabled
    attributes:
      nexus_repository_manager:
        hazelcast:
          multicast:
            enabled: false
          aws:
            enabled: false
          tcp_ip:
            enabled: true
            interface: '10.0.1.1'
            members: ['10.0.1.2', '10.0.1.3', '10.0.1.4']
  - name: aws_enabled
    run_list:
      - recipe[nexus_repository_manager::default]
    verifier:
      inspec_tests:
        - test/smoke/aws_enabled
    attributes:
      nexus_repository_manager:
        hazelcast:
          multicast:
            enabled: false
          tcp_ip:
            enabled: false
          aws:
            enabled: true
            iam_role: "test-iam-role"
            region: "test-region"
            tag_key: "test-tag-key"
            tag_value: "test-tag-value"
        properties:
          clustered: true
          license_file: "/opt/sonatype/license.lic"
  - name: hazelcast_discovery_enabled
    run_list:
      - recipe[nexus_repository_manager::default]
    verifier:
      inspec_tests:
        - test/smoke/hazelcast_discovery_enabled
    attributes:
      nexus_repository_manager:
        hazelcast:
          multicast:
            enabled: false
          tcp_ip:
            enabled: false
          aws:
            enabled: false
          discovery:
            enabled: true
            iam_role: "test-hz-iam-role"
            region: "test-hz-region"
            tag_key: "test-hz-tag-key"
            tag_value: "test-hz-tag-value"
            security_group_name: "test-hz-security-group-name"
            hz_port: 5708
